In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [3]:
np?

In [4]:
#create array
np.array([1,3,4,5,6])

array([1, 3, 4, 5, 6])

In [5]:
np.array([1,2,3,4,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
#multidimenstional array
np.array([range(i,i+3) for i in [2,3,4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Computational on Numpy Arrays: Universal Functions

#### computation time using vectorization through ufuncs are always more efficient than their counterpart

In [7]:
#compute the reciprocal of each element of array
import numpy as np
np.random.seed(0)

In [11]:
def computeReciprocal(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [13]:
values = np.random.randint(1,10, size=5)
print(values)
print(computeReciprocal(values))

[8 8 9 2 6]
[0.125      0.125      0.11111111 0.5        0.16666667]


In [16]:
#compute the execution time
bigArray = np.random.randint(1,100, size = 1000000)
%timeit computeReciprocal(bigArray)
#it takes so much time


7.86 s ± 452 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
#comapre with ufuncs

print(computeReciprocal(values))
print(1.0/values)

[0.125      0.125      0.11111111 0.5        0.16666667]
[0.125      0.125      0.11111111 0.5        0.16666667]


In [19]:
#execution time of ufuncs is very less

%timeit (1.0/bigArray)

16.9 ms ± 1.39 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
%timeit np.arange(5) / np.arange(1,6)

13.9 µs ± 3.27 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
#Create multiplication table using "OUTER PRODUCTS"

x = np.arange(1,10)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

# Aggregation

In [32]:
M = np.random.random((3,5))
M

array([[0.42753478, 0.17775497, 0.40336412, 0.94758051, 0.6038809 ],
       [0.97349607, 0.23047477, 0.49546779, 0.8517873 , 0.65720747],
       [0.62616714, 0.96945095, 0.17664525, 0.69263117, 0.57380881]])

In [33]:
M.sum()

8.80725200318213

In [34]:
M.sum(axis=0)

array([2.027198  , 1.37768069, 1.07547716, 2.49199898, 1.83489718])

In [35]:
M.sum(axis=1)

array([2.56011528, 3.20843341, 3.03870332])

In [36]:
M.min()

0.1766452503336785

In [38]:
M.mean()

0.5871501335454753

In [40]:
M.argmin()

12

In [42]:
a = np.array([[1,2,3],
             [6,3,2],
             [1,0,0]])
a

array([[1, 2, 3],
       [6, 3, 2],
       [1, 0, 0]])

In [43]:
a.min()

0

In [44]:
a.max()

6

In [45]:
a.sum()

18

In [46]:
a.mean()

2.0

In [47]:
a.std()

1.7638342073763937

In [48]:
a.

AttributeError: 'numpy.ndarray' object has no attribute 'median'