In [1]:
import numpy as np

## THe Basics


In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a.ndim  #get shape

1

In [6]:
b = np.array([[9,8,8,1],
             [1,2,7,8]])
print(b)

[[9 8 8 1]
 [1 2 7 8]]


In [7]:
b.shape

(2, 4)

In [8]:
#get type 
a.dtype

dtype('int32')

In [9]:
#get size
a.size

3

In [10]:
a.itemsize

4

In [11]:
b.size

8

In [12]:
b.itemsize

4

In [13]:
b.nbytes

32

# accessing/changing specific elements,rows, columns etc

In [14]:
a = np.array([[1,2,3,4,5,6,7],
             [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
#get specific element
a[1,3]

11

In [18]:
a[0,-3]

5

In [20]:
#get a specif row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#get specific columns
a[:,1]

array([2, 9])

In [25]:
#[startindex:endindex:stepsize]

a[0,1:7:3]

array([2, 5])

In [26]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [29]:
b[0,1,1]

4

In [31]:
b[:,1,:]

array([[3, 4]])

# Initializing different types of array

In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((4,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [39]:
#any other number
# np.full((shape), value)
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [43]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [66]:
#initialize matrix of random numbers
np.random.rand(3,2,2)

array([[[0.50599557, 0.35274538],
        [0.35972458, 0.35515541]],

       [[0.75195898, 0.33014752],
        [0.88446767, 0.60024795]],

       [[0.63715257, 0.79381855],
        [0.61951283, 0.10287032]]])

In [68]:
np.random.random_sample(a.shape)

array([[0.79406336, 0.45019855, 0.19194011, 0.39103258, 0.68995723,
        0.62030954, 0.66267499],
       [0.52153239, 0.897051  , 0.81278324, 0.60431416, 0.02653063,
        0.72679687, 0.17854943]])

In [77]:
#random integer values
np.random.randint(1,9, size=(3,3))

array([[2, 3, 4],
       [8, 6, 8],
       [5, 8, 6]])

In [86]:
np.identity(10)   #the identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [91]:
#repeat an array
arr = np.array([[1,2,3]])

r1 = np.repeat(arr,3, axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### create a matrix
1 1 1 1 1 

1 0 0 0 1

1 0 9 0 1

1 0 0 0 1

1 1 1 1 1 

In [94]:
o = np.ones((5,5))
print(o)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [96]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [98]:
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [100]:
o[1:4, 1:4] = z
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Mathematics

In [101]:
a = np.array([1,2,4,5])
a

array([1, 2, 4, 5])

In [102]:
a+2

array([3, 4, 6, 7])

In [103]:
a-2

array([-1,  0,  2,  3])

In [104]:
a*2

array([ 2,  4,  8, 10])

In [105]:
a/2

array([0.5, 1. , 2. , 2.5])

In [106]:
a*a

array([ 1,  4, 16, 25])

In [107]:
a*a*a*a

array([  1,  16, 256, 625])

In [109]:
b = np.array([1,1,1,1])

In [110]:
a+b

array([2, 3, 5, 6])

In [111]:
a*b

array([1, 2, 4, 5])

In [113]:
a**3

array([  1,   8,  64, 125], dtype=int32)

In [114]:
#take sin
np.sin(a)

array([ 0.84147098,  0.90929743, -0.7568025 , -0.95892427])

In [115]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.65364362,  0.28366219])

#### Linear Algebra

In [117]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
b = np.full((3,2), 4)
b

array([[4, 4],
       [4, 4],
       [4, 4]])

In [121]:
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])

In [122]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.linalg.det(c)  #find determinent

1.0

#### Statistics

In [124]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
np.min(stats)

1

In [126]:
np.max(stats,axis=0)

array([4, 5, 6])

In [128]:
np.min(stats, axis=1)

array([1, 4])

### Reorganizing Arrays

In [129]:
before = np.array([[1,2,3,4],
                  [6,7,8,9]])
before

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [130]:
before.shape

(2, 4)

In [ ]:
#make this to 8,1 shape

In [131]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [8],
       [9]])

In [135]:
before.reshape((1,1,8))

array([[[1, 2, 3, 4, 6, 7, 8, 9]]])

In [136]:

#vertically stacking vectors or matrices
v1 = np.array([1,2,3,4])
v2 = np.array([3,4,5,2])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [3, 4, 5, 2]])

In [137]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [3, 4, 5, 2],
       [3, 4, 5, 2],
       [1, 2, 3, 4]])

In [141]:
#horizontal stack
h1 = np.ones((2,3))
h2 = np.zeros((2,2))

np.hstack([h1,h2,h1])

array([[1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.]])

## Miscellaneous

#### load data from file

In [149]:
fileData = np.genfromtxt('data.txt', delimiter = ',')
fileData

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [160]:
# print(fileData.astype('int32'))
fileData = fileData.astype('int32')
fileData

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### advance indeixng

In [155]:
fileData>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [156]:
fileData[fileData > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [159]:
np.any(fileData > 50, axis =1)

array([ True,  True,  True])

In [167]:
((fileData>50) ^ (fileData <20))

array([[ True,  True, False,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

### some more

In [168]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25],
             [26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [171]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [175]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [178]:
a[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])