# Introduction
In this model we will predict whether the movie will win the oscer or not.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#load dataset
df = pd.read_csv("D:\\pkworkspace\\100DaysDataScience\\datasets\\Movie_classification.csv", header =0)

In [5]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### MIssing value

In [10]:
df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace = True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### DUMMY VARIABLE CREATION

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [15]:
df = pd.get_dummies(df, columns = ['3D_available','Genre'], drop_first=True)

In [18]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  Time_taken           506 non-null    float64
 12  Twitter_hastags      506 non-null    float64
 13  Avg_age_actors       506 non-null    int64  
 14  Num_multiplex        506 non-null    int64  
 15  Collection           506 non-null    int

In [19]:
x = df.loc[:, df.columns!= 'Start_Tech_Oscar']
y = df['Start_Tech_Oscar']

### Train test split

In [21]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train,y_test = train_test_split(x,y, test_size = 0.3, random_state=0)

### Standardize data

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc = StandardScaler().fit(x_train)

In [27]:
x_train_std = sc.transform(x_train)

In [28]:
x_test_std = sc.transform(x_test)

In [29]:
x_test_std.shape

(152, 20)

In [31]:
from sklearn import svm

In [65]:
svmClf = svm.SVC(kernel = "linear", C = 0.2)

In [66]:
svmClf.fit(x_train_std, y_train)

SVC(C=0.2, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

### PRedict Values

In [67]:
y_train_pred = svmClf.predict(x_train_std)
y_test_pred = svmClf.predict(x_test_std)

In [68]:
y_test_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1],
      dtype=int64)

## MOdle Performance

In [69]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [70]:
confusion_matrix(y_test, y_test_pred)

array([[39, 24],
       [34, 55]], dtype=int64)

In [71]:
accuracy_score(y_test, y_test_pred)

0.618421052631579

In [72]:
# to get number of support vectors

svmClf.n_support_

array([138, 138])

### Grid Search
This is used to get the optimised value of C

In [73]:
from sklearn.model_selection import GridSearchCV

In [74]:
params = {'C':(0.001, 0.002, 0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10,100,200,1000)}

In [76]:
svmClf = svm.SVC(kernel='linear')  

In [77]:
svmGridLin = GridSearchCV(svmClf, params, n_jobs = -1,
                         cv = 10, verbose=1, scoring='accuracy')

In [78]:
svmGridLin.fit(x_train_std, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 130 out of 130 | elapsed:  4.9min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': (0.001, 0.002, 0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10,
                               100, 200, 1000)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [80]:
svmGridLin.best_params_

{'C': 0.1}

In [83]:
# this will give the best model

linSvmClf = svmGridLin.best_estimator_

In [84]:
linSvmClf

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [86]:
accuracy_score(y_test, linSvmClf.predict(x_test_std)) * 100

59.86842105263158

# Other SVM Classes

## Radial

In [87]:
clf_svm_radial = svm.SVC(kernel='rbf', gamma=0.5, C=10)
clf_svm_radial.fit(x_train_std, y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [88]:
y_train_pred = clf_svm_radial.predict(x_train_std)
y_test_pred = clf_svm_radial.predict(x_test_std)

In [89]:
accuracy_score(y_test, y_test_pred)

0.618421052631579

In [90]:
clf_svm_radial.n_support_

array([167, 187])

## Radial Grid

In [92]:
params = {'C': (0.01, 0.05,0.1, 0.5, 1, 4, 10, 50),
         'gamma':(0.001, 0.0001, 0.01, 0.1, 0, 0.5,1)}

In [93]:
clf_svm_radial = svm.SVC(kernel='rbf')

In [94]:
svmGrid_radial = GridSearchCV(clf_svm_radial, params, n_jobs = -1,
                             cv=3, verbose=1, scoring='accuracy')

In [95]:
svmGrid_radial.fit(x_train_std, y_train)

Fitting 3 folds for each of 56 candidates, totalling 168 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 168 out of 168 | elapsed:  1.3min finished


GridSearchCV(cv=3, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 4, 10, 50),
                         'gamma': (0.001, 0.0001, 0.01, 0.1, 0, 0.5, 1)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [96]:
svmGrid_radial.best_params_

{'C': 50, 'gamma': 0.001}

In [97]:
radsvm_Clf = svmGrid_radial.best_estimator_

In [99]:
accuracy_score(y_test, radsvm_Clf.predict(x_test_std))

0.5855263157894737